<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_OLX</name>
   <tag></tag>
   <elementGuidId>538c038d-0a38-446c-9251-a6afc3dfb064</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]/div/div[2]/div[4]/div/div/div/div/div/button/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-molecules-agent-portal-listing__card ui-atomic-card ui-atomic-card--rounded ui-atomic-card--type-border shadow--effect-default-1 shadow--effect-default-1--disable-hover</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OLX</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;ui-template-admin&quot;]/div[@class=&quot;ui-template-admin__content p-25&quot;]/div[@class=&quot;row ui-pages-listing flex&quot;]/div[@class=&quot;col-13 pl-25 ui-pages-listing__content&quot;]/div[@class=&quot;ui-molecules-dialog-post flex ui-atomic-dialog ui-atomic-dialog--type-popup fade-enter-done&quot;]/div[@class=&quot;ui-atomic-dialog__content absolute flex no-m fade-scale-center-enter-done&quot;]/div[@class=&quot;ui-molecules-dialog-post__upperBlock flex&quot;]/div[@class=&quot;ui-molecules-dialog-post__agentPortalWrap flex&quot;]/div[1]/div[@class=&quot;ui-molecules-agent-portal-listing&quot;]/button[@class=&quot;ui-molecules-agent-portal-listing__cardBtn&quot;]/div[@class=&quot;ui-molecules-agent-portal-listing__card ui-atomic-card ui-atomic-card--rounded ui-atomic-card--type-border shadow--effect-default-1 shadow--effect-default-1--disable-hover&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div/div[2]/div[4]/div/div/div/div/div/button/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cross Post'])[3]/following::div[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='close'])[1]/following::div[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Team Jaktu'])[1]/preceding::div[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Team Jakut'])[1]/preceding::div[12]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/div</value>
   </webElementXpaths>
</WebElementEntity>
